theme: jekyll-theme-hacker

url: "https://protogencollection.titusstudios.net/" # the hostname & protocol for your site
title: Open Source Protogen Collection
description: Creating FOSS Protogen Setups For Everyone, All the resources for building your own Protogen Fursuit.
logo: /data/static/images/icon-transparent.png
gems: 
      - jemoji
      - jekyll-sitemap
      - jekyll-paginate
      
defaults:
  -
    scope:
      path:            "assets/*"
      path:            "data/*"
    values:
      sitemap:         false

paginate: 5
paginate_path: "/blog/page:num/"
